### ISSUE TITLE
Find real-world application for CBTSP

### ISSUE THREAD

**Issue by mau14333** [moritzmacke/heuopt20#1]
1.  Can you think of a real-world application for this problem?
*Hint: A more general problem is to find a Hamiltonian cycle with cost closest to some value x. This problem can be reduced to the CBTSP by transforming edge costs via d_{i,j}=d′_{i,j}−x/|V|.*

**Comment by mau14333** [comment]
Eine mögliche Idee: Eine Reise bei der man ein gewisses Budget möglichst genau verbrauchen will, und aus irgendeinem Grund gibt es mögliche Strecken auf denen man Geld verdient (z.B. weil man mit einem Elektroauto fährt und die Straßen dort wireless charging machen).

**Comment by moritzmacke** [comment]
Das mit der Tour, das jetzt im Bericht steht scheint mir zu passen. Gute Idee!
