### ISSUE TITLE
Define formula for big-M constant

### ISSUE THREAD

**Issue by mau14333** [moritzmacke/heuopt20#2]
2. Give a formula to calculate a reasonable big-M constant M∈N for a given graph G with edge weights d_{i,j}. Prove that when using M as weights for all non-existing edges, the objective of any “infeasible” solution is greater than the objective of every feasible solution.

**Comment by mau14333** [comment]
Formel und Beweis sind im Protokoll vorhanden - meiner Meinung nach damit erledigt.

**Comment by moritzmacke** [comment]
Ja, passt.
