### ISSUE TITLE
Construct infeasible 2-opt solution

### ISSUE THREAD

**Issue by mau14333** [moritzmacke/heuopt20#3]
3. Construct  a  Hamiltonian graph G with  edge  costs  and  an  “infeasible”  solution  that  is  a  2-opt solution, i.e., a solution that cannot be improved by the exchange of two edges.

**Comment by moritzmacke** [comment]
Denke ich habe jetzt was.
Graph mit 7 Knoten und Kanten zwischen (1..2..3..4..5..6..7..1) plus (5..7) mit gleichem Gewicht.
Lösung [1,2,6,3,4,5,7] hat zwei infeasible edges (2..6,6..3) und jeder mögliche 2opt move mit einer dieser Kanten erzeugt wieder mindestens eine invalide Kante, so dass Lösung nicht besser werden kann.

**Comment by mau14333** [comment]
Hab mir das auch mal aufgezeichnet, dürfte stimmen. Der Versuch die (2..6) edge durch eine valide zu ersetzen handelt einem entweder (1..6) oder (6..4) ein, je nachdem ob man 1 oder 3 hinter die 2 bringen will. Bei (6..3) kann man die 5 hinter 6 bringen und (3..7) bekommen oder die 7 dahinterbringen und  (3..1) bekommen. Mehr als die 4 Fälle braucht man glaub ich gar nicht für eine vollständige Argumentation, weil das die einzigen moves sind, die überhaupt was gegen die ursprünglichen invalid edges tun.
