### ISSUE TITLE
Develop deterministic construction heuristic

### ISSUE THREAD

**Issue by mau14333** [moritzmacke/heuopt20#4]
4.  Develop a meaningful deterministic construction heuristic

**Comment by moritzmacke** [comment]
Gibt da jetzt zwei sinnvolle. Die greedy edge selection und die Hamilton path heuristic. Wäre vielleicht noch zu schauen, ob die zweite verbessert werden kann so, dass sie bei allen eine valide Lösung findet.

**Comment by moritzmacke** [comment]
Done.
