### ISSUE TITLE
Develop randomized construction heuristic

### ISSUE THREAD

**Issue by mau14333** [moritzmacke/heuopt20#5]
5. Develop a randomized construction heuristic to be applied iteratively.

**Comment by moritzmacke** [comment]
Denke die Greedy Edge selection Heuristik funktioniert gut genug. Aber vielleicht kann man noch was verbessern, um die Zahl der infeasible edges zu minimieren.

**Comment by moritzmacke** [comment]
Gut genug würde ich sagen.
