### ISSUE TITLE
Develop/use local search framework

### ISSUE THREAD

**Issue by mau14333** [moritzmacke/heuopt20#6]
6. Develop or make use of a framework for basic local search which is able to deal with
* different neighborhood structures
* different step functions (first-improvement, best-improvement, random)

**Comment by moritzmacke** [comment]
Also die GVNS Klasse sollte man für local search verwenden können, einfach nur eine local improve methode übergeben (dann fällt VND weg) und shake function, die nichts macht. Mit best und first improvement sucht es dann allerdings nur bis zum ersten Optimum.
