### ISSUE TITLE
Develop different neighborhood structures

### ISSUE THREAD

**Issue by mau14333** [moritzmacke/heuopt20#7]
7. Develop at least three different neighborhood structures.

**Comment by mau14333** [comment]
Aktuell implementiert sind die Standard-Neighborhoods:
1. 2-opt
1. 3-opt/block move
1. short block move

Wollen wir noch was ausgefallerenes?

**Comment by moritzmacke** [comment]
Könnten noch Lin-Kernighan machen, wenn es nicht zu kompliziert ist. Ansonsten wären noch die search Funktionen, die diese neighborhoods benutzen zu implementieren.

**Comment by moritzmacke** [comment]
Eh, schaut kompliziert aus. Habe Suche implementiert, die mit allen neighborhoods gehen sollte. Fehlen nur noch die Methoden, um 3-opt und short block zu enumerieren.

**Comment by moritzmacke** [comment]
Habe noch node exchange und single node move/insert implementiert. Auch 2.5 opt, aber wohl nicht nötig da eigentlich ziemlich das selbe wie 2opt + single move in Folge durchsuchen. 
Das zu jedem move einen inversen generieren war wohl von mir auch nicht so sinnvoll, denke wäre besser eine inverse apply function zu definieren wo nötig, aber auch keine Lust das nochmal zu ändern.

**Comment by moritzmacke** [comment]
Erledigt, denke ich. Müssen uns nur noch überlegen, welche wir wo verwenden...
